### ISSUE TITLE
Clear subtitles text

### ISSUE THREAD

**Issue by RSATom** [jaruba/WebChimeraPlayer#2]
https://github.com/RSATom/WebChimera/issues/67

**Comment by jaruba** [comment]
I added it to the repo:

https://github.com/jaruba/WebChimeraPlayer/commit/4f2ef3b1c28f1f2222494a50695cca8ac0869dd6

Thanks!

I'm also planning to try to make an upload subtitle button inside the player. It's a bit tricky to do with pure javascript though because not all browsers support the ```FileReader``` api.

**Comment by zxvfbg** [comment]
Cool Jaruba :)

I think that better solution will be if you make a Subtitles button next to the Fullscreen button which will support array of subtitles with urls and at the start you can place option Upload. Actually the FileReader is not supported only in IE 8 and 9 and we can think of workaround there (something like uploading to public host). If you can make that button i can provide javascript snippet who search in opensubtitles.org and getsubtitle.com by the file hash (i suppose that if the browser support FileReader API i can calculate the hash)

Thanks :)

**Comment by jaruba** [comment]
I'm curious about how getting the hash of a file would work, WebChimera accepts a lot of video sources, I guess this would only work for http video sources...

Best would be to get as much information as possible about the video (name, size and hash). I've seen an interesting example of this done with JS: [here](https://github.com/marcu87/hashme).

But that is made to work with uploaded files, the thing I like about it is that it only reads the first and the last 64kb of the file in order to determine the hash.

I will try to make the subtitle button until the next release of the player, and add a way to add subtitle files to each video element with the .addPlaylist() function.

**Comment by zxvfbg** [comment]
Actually if you have the file local you can generate the hash with some of these:

http://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes

In the next version of Player please think about possibility to have more than one version of subtitles per file (for different languages for example)

**Comment by jaruba** [comment]
Well of course, if I make a subtitle playlist button it should have multiple subtitles per video file, I should also try to add the internal video's subtitles (like those in .mkv files) in that list..

About those codes, they all presume we have the file locally, which we don't.. we have it on a http source, and libvlc (used in WebChimera Plugin) does not save the files locally when streaming, it only keeps the loaded [buffer](http://wiki.webchimera.org/Buffer_Parameter).

So the question is how to download only the first and last 64 kb of a video file from a http source to calculate the hash. (in javascript)

Because we can't download the entire file, some can have more then 1gb.

**Comment by jaruba** [comment]
I can't find any demo from anyone who made a hash calculator for a remote file in JS. Even if we had the video file locally, we would still need user interaction (input, drag and drop) in order to get access to the video on the local file system. (this is for security reasons)

I don't see any way of getting the hash from a video at the moment, I may be wrong though. It would still be possible to use opensubtitles by tag (filename) and moviebytesize. (if we find a way to get this info from the video source)

Otherwise, if this is only possible on the plugin side, maybe @RSATom would want to implement the needed video information in the ```MediaDescription``` object of the JS API.

**Comment by zxvfbg** [comment]
You are right that there is no way to read the end of the through http for example, but in my case (i am making torrent play application like popcorntime.io) it will be usefull. If you have a data storage with collection of movies for example will be also usefull. Today i will try to patch a module for chromecast with javascript and i will try to implement it in WebChimera Player which also be nice :)

**Comment by jaruba** [comment]
Give me your email, I can help you more then you think, but this thread is not the place to talk about it.

**Comment by zxvfbg** [comment]
ivo@adnet.bg

**Comment by jaruba** [comment]
[Subtitle Parameter]( http://wiki.webchimera.org/Subtitles_Parameter ) and a Subtitle Menu have been added to:
https://github.com/jaruba/WebChimeraPlayer/releases/tag/v0.99

**Comment by nilparra** [comment]
zxvfbg, I'm very interresting for a module for chromecast. Can you share it ?
